# Generated by Django 4.1.9 on 2023-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categorie(s)"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Body of the Comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date the Comment was posted"
            ),
        ),
    ]
