# Generated by Django 4.1.9 on 2023-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Add an image of the project.', null=True, upload_to='portfolio/'),
        ),
    ]
