# Generated by Django 4.1.9 on 2023-09-15 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_project_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="image",
            new_name="main_image",
        ),
    ]
