# Generated by Django 4.1.9 on 2023-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_rename_image_project_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Add an image of the project.",
                null=True,
                upload_to="portfolio/",
                verbose_name="Main Image",
            ),
        ),
    ]
