# Generated by Django 4.1.9 on 2023-10-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_projectimage_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name_plural': 'Project Images'},
        ),
    ]
