# Generated by Django 4.1.9 on 2023-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projectimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, help_text="Enter the URL of the project's repository.", null=True, verbose_name='Repository URL'),
        ),
    ]
